import Header from "./components/Header";
import "./globals.css";
import { Inter } from "next/font/google";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "IMDB Nextjs",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        {/*Header*/
          <Header/>
        }

        {/*Navbar*/}

        {/*Search Box*/}
        {children}
      </body>
    </html>
  );
}
